[theme]
primaryColor = "#1DA1F2"
backgroundColor = "#15202B"
secondaryBackgroundColor = "#192734"
textColor = "#E7E9EA"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
